In [1]:
'''


### Q1. What is a database? Differentiate between SQL and NoSQL databases.

A **database** is a structured collection of data that allows for efficient storage, retrieval, and management.

- **SQL Databases**:  
  - Relational, table-based.
  - Uses SQL for querying.
  - Fixed schema.
  - Good for complex queries.
  
- **NoSQL Databases**:  
  - Non-relational, flexible models.
  - No fixed query language.
  - Schema-less.
  - Best for unstructured data and scalability.

---

### Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.

**DDL (Data Definition Language)** is used to define and manage database structures.

- **CREATE**: Creates new objects (e.g., tables).  
  Example: `CREATE TABLE students (id INT, name VARCHAR(50));`
  
- **DROP**: Deletes objects.  
  Example: `DROP TABLE students;`
  
- **ALTER**: Modifies existing structures.  
  Example: `ALTER TABLE students ADD age INT;`
  
- **TRUNCATE**: Removes all data from a table without deleting the structure.  
  Example: `TRUNCATE TABLE students;`

---

### Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.

**DML (Data Manipulation Language)** is used for manipulating data within tables.

- **INSERT**: Adds new data.  
  Example: `INSERT INTO students (id, name) VALUES (1, 'Alice');`
  
- **UPDATE**: Modifies existing data.  
  Example: `UPDATE students SET name = 'Bob' WHERE id = 1;`
  
- **DELETE**: Removes data.  
  Example: `DELETE FROM students WHERE id = 1;`

---

### Q4. What is DQL? Explain SELECT with an example.

**DQL (Data Query Language)** is used for querying data from the database.

- **SELECT**: Retrieves data.  
  Example: `SELECT * FROM students WHERE id = 1;`

---

### Q5. Explain Primary Key and Foreign Key.

- **Primary Key**: A unique identifier for each record in a table (e.g., `id` column). Ensures uniqueness and no null values.
- **Foreign Key**: A column that creates a link between two tables by referencing the primary key in another table.

---

### Q7. Give the order of execution of SQL clauses in an SQL query.

1. **FROM**
2. **WHERE**
3. **GROUP BY**
4. **HAVING**
5. **SELECT**
6. **ORDER BY**
7. **LIMIT** (or OFFSET)

SyntaxError: incomplete input (1849355075.py, line 1)

In [ ]:

### Q6. Write a Python code to connect MySQL to Python. Explain the `cursor()` and `execute()` method.

```python
import mysql.connector

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="your_username",
    password="your_password",
    database="your_database"
)

# Create a cursor object
cursor = conn.cursor()

# Execute a query
cursor.execute("SELECT * FROM students")

# Fetch results
for row in cursor.fetchall():
    print(row)

# Close the connection
conn.close()
```

- **`cursor()`**: Creates a cursor object to execute SQL queries.
- **`execute()`**: Executes an SQL query.

---